#!/etc/bash

alias ..='cd ../'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'

alias ls='ls --color=auto'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

alias ll='ls -l'
alias la='ls -la'
alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

alias c='clear'
alias e='exit'

alias s='$HOME/.dotfiles/linux/connect-ssh.sh'
alias u='$HOME/.dotfiles/linux/update-system.sh'

# git
alias g='git'
alias ga='git add'
alias gc='git commit -v'
alias gcm='git commit -m'
alias gl='git pull'
alias gp='git push'

# docker
alias d='docker'
alias dcd='docker down'
alias dcp='docker pull'
alias dcu='docker compose up'
alias dcud='docker compose up -d --force-recreate'
alias dcuf='docker compose up --force-recreate'
alias dps='docker ps'


function extract () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xvjf $1  ;;
      *.tar.gz)    tar xvzf $1  ;;
      *.tar.xz)    tar xvf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xvf $1   ;;
      *.tbz2)      tar xvjf $1  ;;
      *.tgz)       tar xvzf $1  ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "Extension not recognized, cannot extract $1" ;;
    esac
  else
    echo "$1 is not a valid file"
  fi
}
